[package]
name = "plusendi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aliri_braid = "*"
color-eyre = "*"
lazy-regex = "*"
regex = "*"
serialport = "*"
thiserror = "*"
#tui = "*"
